name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - run: npm i
      - run: npm run build
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        name: Deploy to Netlify
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: _site
          NETLIFY_DEPLOY_MESSAGE: "Deployed commit ${{ github.sha }}"
